name: Publish package to GitHub Packages

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout branch: ${{ github.REF }}.'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting.
          fetch-depth: 0
          ref: ${{ github.HEAD_REF }}
      - name: 'Setup Java environment.'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: jdk
      - name: 'Validate Gradle Wrapper'
        uses: gradle/wrapper-validation-action@v1
      - name: 'Publish package ${{ github.event.release.tag_name }}.'
        run: |
          sed -i "/^project_version=./c\project_version=$TAG" gradle.properties
          ./gradlew --no-daemon --stacktrace publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
